### ISSUE TITLE
missing code of conduct

### ISSUE THREAD

**Issue by krtr** [onatm/right-pad#1]
can someone fix this
(we cannot allow any kind of opression)

**Comment by onatm** [comment]
I can't reproduce that. Can you give me more details? @krtr

**Comment by krtr** [comment]
please, stop oppressing me, otherwise I will must inform your employer about your attitude towards non-social normative people

**Comment by onatm** [comment]
Sorry, it is not going to be fixed. Our product road map is already determined.
